# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmquilt < Formula
  desc "Watch a command and generate diffs from the output changes"
  homepage "https://github.com/luisdavim/helmquilt"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luisdavim/helmquilt/releases/download/v0.1.2/helmquilt_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "8c19f1c241e79209bb1bc8216c10816f3dd2f771c3233dbaf2bb88b614f0a743"

      define_method(:install) do
        bin.install "helmquilt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luisdavim/helmquilt/releases/download/v0.1.2/helmquilt_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c22a43cda3db1f93d3eb83cca9da54db4c6166b42f5f82ecf8e2b292f190abfb"

      define_method(:install) do
        bin.install "helmquilt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/helmquilt/releases/download/v0.1.2/helmquilt_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "fa94efcbc32b7f1d421fa7aa611015cae3ebfab2dc2ee3aecd5c26155e7596ca"
      define_method(:install) do
        bin.install "helmquilt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luisdavim/helmquilt/releases/download/v0.1.2/helmquilt_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "14b1cc25a5e5618e4b5644a8a25b7d6e79dcaeb55fbb8be3c26e99a2fc2b6cef"
      define_method(:install) do
        bin.install "helmquilt"
      end
    end
  end

  test do
    system "#{bin}/helmquilt", "-h"
  end
end
